# Generated by Django 3.2.4 on 2021-06-14 11:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flmate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='abrCLEAN',
            field=models.DecimalField(decimal_places=0, default=8, max_digits=2, verbose_name='Кол-во уборок в месяц (0-30):'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aprFRETM',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cafe', 'Кафе'), ('socnet', 'Соц.сети'), ('drinkin', 'Выпивка'), ('cinema', 'Кинотеатр'), ('culture', 'Культурные места: театры, выставки, музеи и т.д'), ('reading', 'Чтение'), ('activity', 'Активный отдых'), ('imprusf', 'Развитие себя'), ('games', 'Игры'), ('study', 'Учеба')], default='imprusf', max_length=71, verbose_name='Cвободное время:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aprR8GEN',
            field=models.CharField(choices=[('man', 'Мужской'), ('inbetween', 'Не имеет значения'), ('woman', 'Женский')], default='inbetween', max_length=20, verbose_name='Пол:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aprR8RELIGY',
            field=models.CharField(choices=[('сhrist', 'Христианство'), ('muslim', 'Ислам'), ('induism', 'Индуизм'), ('budism', 'Будизм'), ('iudaism', 'Иудаизм'), ('pastafarian', 'Пастафарианство'), ('ateism', 'Я считаю себя атеистом'), ('nosing', 'Это не имеет значения')], default='pastafarian', max_length=25, verbose_name='Религия:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/profdef.svg', upload_to='users/%Y/%m/%d', verbose_name='Тут можно загрузить свое фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rmAgeL',
            field=models.DecimalField(decimal_places=0, default=18, max_digits=2, verbose_name='От:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rntLPrice',
            field=models.DecimalField(decimal_places=0, default=10000, max_digits=5, verbose_name='От:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rntSubway',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Кировско-Выборгская', (('1', 'Девяткино'), ('2', 'Гражданский проспект'), ('3', 'Академическая'), ('4', 'Политехническая'), ('5', 'Площадь Мужестват'), ('6', 'Лесная'), ('7', 'Выборгская'), ('8', 'Площадь Ленина'), ('9', 'Чернышевская'), ('10', 'Площадь Восстания'), ('11', 'Владимирская'), ('12', 'Пушкинская'), ('13', 'Технологический институт'), ('14', 'Балтийская'), ('15', 'Нарвская'), ('16', 'Кировский завод'), ('17', 'Автово'), ('18', 'Ленинский проспект'), ('19', 'Проспект Ветеранов'))), ('Московско-Петроградская', (('20', 'Парнас'), ('21', 'Проспект Просвещения'), ('22', 'Озерки'), ('23', 'Удельная'), ('24', 'Пионерская'), ('25', 'Чёрная речка'), ('26', 'Петроградская'), ('27', 'Горьковская'), ('28', 'Невский проспект'), ('29', 'Сенная площадь'), ('30', 'Технологический институт'), ('31', 'Фрунзенская'), ('32', 'Московские ворота'), ('33', 'Электросила'), ('34', 'Парк Победы'), ('35', 'Московская'), ('36', 'Звёздная'), ('37', 'Купчино'))), ('Невско-Василеостровская', (('38', 'Беговая'), ('39', 'Зенит'), ('40', 'Приморская'), ('41', 'Василеостровская'), ('42', 'Гостиный двор'), ('43', 'Маяковская'), ('44', 'Площадь Александра Невского'), ('45', 'Елизаровская'), ('46', 'Ломоносовская'), ('47', 'Пролетарская'), ('48', 'Обухово'), ('49', 'Рыбацкое'))), ('Правобережная', (('50', 'Спасская'), ('51', 'Достоевская'), ('52', 'Лиговский проспект'), ('53', 'Площадь Александра Невского'), ('54', 'Новочеркасская'), ('55', 'Ладожская'), ('56', 'Проспект Большевиков'), ('57', 'Улица Дыбенко'))), ('Фрунзенско-Приморская', (('58', 'Комендантский проспект'), ('59', 'Старая Деревня'), ('60', 'Крестовский остров'), ('61', 'Чкаловская'), ('62', 'Спортивная'), ('63', 'Адмиралтейская'), ('64', 'Садовая'), ('65', 'Звенигородская'), ('66', 'Обводный канал'), ('67', 'Волковская'), ('68', 'Бухарестская'), ('69', 'Международная'), ('70', 'Проспект Славы'), ('71', 'Дунайская'), ('72', 'Шушары')))], default='0', max_length=103, verbose_name='Станции метро:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rntUPrice',
            field=models.DecimalField(decimal_places=0, default=15000, max_digits=5, verbose_name='До:'),
        ),
    ]
