# Generated by Django 3.2.4 on 2021-06-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flmate', '0002_auto_20210614_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='abuORGL',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=2, verbose_name='Уровень организованности (0-10):'),
        ),
    ]
