# Generated by Django 3.2.4 on 2021-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flmate', '0004_auto_20210803_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chatNotif',
            field=models.BooleanField(default=True, verbose_name='Уведомлять меня о новых соседях:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mesNotif',
            field=models.BooleanField(default=True, verbose_name='Уведомлять меня о новых сообщения:'),
        ),
    ]
